# Generated by Django 2.1.1 on 2018-10-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_requestproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
