# Generated by Django 2.1.1 on 2018-10-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='contact',
            field=models.TextField(verbose_name='Datos de contacto. Puedes escribir una dirección incluyendo número telefónico, o solo el número telefónico. Esta información será visible y se le enviara a la persona que hayas aceptado entregarle el producto.'),
        ),
    ]
