# Generated by Django 2.1.1 on 2018-10-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20181027_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportproduct',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
