# Generated by Django 2.1.1 on 2018-10-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_reportproduct_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestproduct',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
    ]
