# Generated by Django 2.1.1 on 2018-11-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_flyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='flyer',
            field=models.ImageField(default='static/img/placeholder.gif', upload_to='event_flyer'),
        ),
    ]
