# Generated by Django 2.1.1 on 2018-11-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20181101_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='flyer',
            field=models.ImageField(default='/placeholder.gif', upload_to='event_flyer'),
        ),
    ]
