# Generated by Django 2.1.1 on 2018-10-27 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_auto_20181025_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsemessage',
            name='parent_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_message', to='inbox.Message'),
        ),
    ]
